// Example script to be used by Claude Code to search for dependencies
const axios = require('axios');
const fs = require('fs');

async function discoverDependencies(searchTerms) {
  try {
    const response = await axios.post('http://mcp-server:4000/api/dependencies/discover', {
      searchTerms: searchTerms
    });
    
    return response.data.dependencies;
  } catch (error) {
    console.error('Error discovering dependencies:', error.message);
    return [];
  }
}

async function main() {
  // Read search terms from analysis.md (generated by Claude Code)
  const analysisContent = fs.readFileSync('analysis.md', 'utf8');
  
  // Extract affected components from analysis
  const affectedComponents = /* parsing logic */;
  
  // Generate search terms based on affected components
  const searchTerms = affectedComponents.map(component => `import.*${component}`);
  
  // Add additional search terms for configuration references
  searchTerms.push(...affectedComponents.map(component => `config.*${component}`));
  
  // Discover dependencies
  const dependencies = await discoverDependencies(searchTerms);
  
  // Generate dependencies.md
  let dependenciesMarkdown = '# Dependencies\n\n';
  dependenciesMarkdown += 'The following repositories are affected by this bug:\n\n';
  
  dependencies.forEach(repo => {
    dependenciesMarkdown += `## ${repo.name}\n\n`;
    dependenciesMarkdown += 'Matched files:\n\n';
    
    repo.matchedFiles.forEach(file => {
      dependenciesMarkdown += `- ${file.path}: ${file.url}\n`;
    });
    
    dependenciesMarkdown += '\n';
  });
  
  fs.writeFileSync('dependencies.md', dependenciesMarkdown);
  console.log('Dependencies document generated successfully');
}

main().catch(console.error);
